title: CHIJ Katong Convent
url: https://chijkatongconvent.moe.edu.sg
favicon: /images/CHIJOLGC Crest (Mini).png
colors:
  primary-color: "#3d49a4"
  secondary-color: "#3d49a4"
  media-colors:
    - title: media-color-one
      color: "#b70218"
    - title: media-color-two
      color: "#182061"
    - title: media-color-three
      color: "#3d49a4"
    - title: media-color-four
      color: "#9b9b9b"
    - title: media-color-five
      color: "#b70218"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dmkpqrrm2djqs.amplifyapp.com
prod: https://master.dmkpqrrm2djqs.amplifyapp.com
shareicon: /images/photo1668247779.jpeg
is_government: true
facebook-pixel: ""
google_analytics: G-KPJ9STF5ER
linkedin-insights: ""
resources_name: media
